name: Escaneo de seguridad con skims (machine standalone CLI)
on: [push, pull_request]
jobs:
   machineStandalone:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
         - name: Ejecutar CLI
           uses: docker://docker.io/fluidattacks/cli:latest           
           with:
             args: skims scan config/config.yaml

         - name: Crear artefeacto con resultados en formato CSV
           if: always()
           uses: actions/upload-artifact@v2
           with:
              name: resultados
              path: results.csv
